language: cpp

compiler:
  - gcc
  - clang

os:
 - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-6
      - clang-3.6

script:
  - cmake -H. -B_build
  - cmake --build _build
